# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_churon_wrappers", use_symbols = TRUE, package_name = "churon")

#' @docType package
#' @usage NULL
#' @useDynLib churon, .registration = TRUE
NULL

RSession <- new.env(parent = emptyenv())

RSession$new <- function() .Call(wrap__RSession__new)

RSession$model_for_path <- function(path) .Call(wrap__RSession__model_for_path, self, path)

#' @export
`$.RSession` <- function (self, name) { func <- RSession[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RSession` <- `$.RSession`


# nolint end
