# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_churon_wrappers", use_symbols = TRUE, package_name = "churon")

#' @docType package
#' @usage NULL
#' @useDynLib churon, .registration = TRUE
NULL

RSession <- new.env(parent = emptyenv())

RSession$from_path <- function(path) .Call(wrap__RSession__from_path, path)

RSession$check_input <- function() invisible(.Call(wrap__RSession__check_input, self))

#' @export
`$.RSession` <- function (self, name) { func <- RSession[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RSession` <- `$.RSession`


# nolint end
