name: R formatting

on:
  pull_request:

permissions: read-all

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: posit-dev/setup-air@cf390573ff4fe0f198f35df3a642b1409328d859

      - run: air format . --check
